### ISSUE TITLE
(已解决)由于部分电脑兼容性问题造成的角色模型无法加载且5261界面为黑屏的解决方案

### ISSUE THREAD

**Issue by jzhj123** [swordswind/ai_virtual_mate_web#1]
![屏幕截图 2024-07-15 210652](https://github.com/user-attachments/assets/5102f404-92a3-4495-a2af-3acb213b7fbf)

电脑：联想拯救者y7000p 2020/2024（两台都试过）
处理器：Intel(R) Core(TM) i7-14700HX   2.10 GHz
操作系统：Windows 11

**Comment by swordswind** [comment]
如果大家遇到了同样的问题，可对Python代码进行调试，并上报电脑型号、操作系统等信息到本issue

**Comment by jzhj123** [comment]
通过开发者工具，发现5261有这个错误
live2d.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by jzhj123** [comment]
### 修改html文件可以解决
<!DOCTYPE html>
<html lang="zh">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/png" href="assets/image/logo.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
      body {
        background-color: black;
      }
      #canvas2 {
        width: 60%;
        height: auto;
        margin: 50px auto;
        display: block;
      }
    </style>
    <script src="https://cubism.live2d.com/sdk-web/cubismcore/live2dcubismcore.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/dylanNew/live2d/webgl/Live2D/lib/live2d.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/pixi.js@6.5.2/dist/browser/pixi.min.js"></script>
    <title>角色 - AI虚拟伙伴</title>
    <script type="module">
      // 在此处粘贴 live2d.js 的内容
    </script>
  </head>
  <body>
    <div id="app"></div>
    <canvas id="canvas2"></canvas>
  </body>
</html>
