### ISSUE TITLE
项目运行依赖问题

### ISSUE THREAD

**Issue by buptxinghan** [swordswind/ai_virtual_mate_web#2]
在安装依赖包时遇到以下报错：
ERROR: Cannot install -r requirements.txt (line 10), -r requirements.txt (line 6), httpx==0.24.1 and ollama==0.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested httpx==0.24.1
    gradio-client 1.0.2 depends on httpx>=0.24.1
    openai 1.35.10 depends on httpx<1 and >=0.23.0
    ollama 0.2.1 depends on httpx<0.28.0 and >=0.27.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by swordswind** [comment]
一个月前项目发布时不存在此报错，由于最近httpx更新造成此问题。经刚刚查实，该报错不影响使用，分别单独安装这些库即可
